# tomcat.connection-timeout how long to wait between tcp ack and receiving http request
server:
  port: 9001
  tomcat:
    connection-timeout: 2s # default is 20s
    keep-alive-timeout: 15s
    threads:
      max: 30 # decrease resources usage. default 200
      min-spare: 3 # default 10

polar:
  greeting: "Welcome to the local book catalog."
  